name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: "0 6 * * *"   # 1 vez al día
  workflow_dispatch:       # permitir correrlo a mano

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # con esto basta
        with:
          USERNAME: Harold9893
          BRANCH_NAME: output
          AUTO_PUSH: true
